### ISSUE TITLE
useElementScroll is deprecated

### ISSUE THREAD

**Issue by ysj151215** [malerba118/scrollex#11]
Current version: v2.0.0

Error message:
> useElementScroll is deprecated. Convert to useScroll({ container: ref }).
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.

**Comment by agbales** [comment]
Ran into this error today, and it appears to come from Scrollex's use in `useScroll.tsx`. I haven't tested yet @malerba118, but I believe updating `useElementScroll` to framer-motion [useScroll](https://www.framer.com/docs/use-scroll/) would resolve.

**Comment by malerba118** [comment]
hey guys, will get a fix in for this shortly 👍

**Comment by malerba118** [comment]
Fixed in 2.0.1!
