### ISSUE TITLE
Enable elements above and below Scroll.Container to scroll naturally

### ISSUE THREAD

**Issue by jamezening** [malerba118/scrollex#8]
Thank you for the cool package 😎

Is there a way to enable elements above the `Scroll.Container` to scroll naturally in the browser?

If I add components outside and below `Scroll.Container`, the components I add scroll **over** the Scroll.Container without pushing it upwards.

I am probably missing out on something, but any help / tips would be appreciated 😊

**Comment by malerba118** [comment]
Hmm, i don't quite understand what you're attempting to do.

The `Scroll.Container` will always create a new scrollable region. 

It's alway possible to put the content inside of the `Scroll.Container` but add no animations to it and then it will just behave as ordinary scrollable content.

If you put content outside of the `Scroll.Container` it will be a part of another scrollable region and you'll end up with two scroll bars.
